- client/src/components/company-input/company-input.tsx
feat: auto-populate fields from url parameters
> Populate fields

- backend/backend/settings.py
- backend/secretshare/mpce.py
- backend/tests/test_primality.py
- client/src/components/session-create/session-create.tsx
- client/src/components/session-manage/generate-link.tsx
- client/src/services/api.ts
Solve CORS issue, correct parameter names and display generated urls
> Integrate generate_urls api

- client/.env.local
- client/src/components/training-banner.tsx
- client/src/layouts/layout.tsx
> feat: add training env banner

- client/src/components/submission-alert.tsx
- client/src/components/verify-data.tsx
> Proper Submit Status

- client/src/constants/default-data.ts
- client/src/pages/home.tsx
> Default Data Added

- client/src/components/session-manage/session-manage-table.tsx
- client/src/components/session-manage/session-manage.tsx
- client/src/components/session-manage/table.tsx
> Manage tbl

- client/src/components/table.tsx
> Shadow added

- backend/backend/apis/bwwc.py
- backend/secretshare/mpce.py
- client/src/components/forms/text-input.tsx
- client/src/components/session-create/session-create.tsx
- client/src/components/session-manage/generate-link.tsx
- client/src/components/session-manage/session-manage.tsx
- client/src/components/verify-data.tsx
- client/src/pages/home.tsx
- client/src/services/api.tsx
Fix undefined sessionId passed to createNewSubmissionUrls()
> Fix AppContext.Provider

- client/src/pages/home.tsx
> Default Data added back

- backend/backend/apis/bwwc.py
- backend/secretshare/mpce.py
- client/src/components/session-create/session-create.tsx
- client/src/components/submission-alert.tsx
- client/src/components/verify-data.tsx
- client/src/pages/home.tsx
- client/src/redux/session.tsx
- client/src/services/api.tsx
Update client to show alert when data submission is closed.
> Data submission closed alert

- backend/backend/apis/bwwc.py
- backend/env/.env.dev
- backend/env/.env.example
- backend/secretshare/mpce.py
- client/src/pages/home.tsx
- client/src/services/api.tsx
Merge main and disable read-only
> Disable read-only

- client/src/utils/csv-parser.ts
> CSV parser fixed

- client/src/components/session-manage/generate-link.tsx
> NewLine added and colons removed

- backend/backend/apis/bwwc.py
- client/src/services/api.tsx
Add auth_token for getting submission history
> feat: add auth_token param

- client/src/guards/admin.guard.tsx
> fix: uncomment auth guard

- client/src/components/session-decrypt/decrypt-input.tsx
> fix: off by one progress bar

- backend/backend/apis/bwwc.py
- backend/secretshare/mpce.py
- backend/tests/test_mpce.py
- client/src/components/session-decrypt/decrypt-input.tsx
- client/src/redux/session.tsx
- client/src/services/api.tsx
Sum metadata and make available via `get_submitted_data` endpoint and save to redux in front end
> feat: metadata endpoint

- README.md
- backend/secretshare/mpce.py
- client/src/components/session-result/session-result.tsx
- client/src/guards/admin.guard.tsx
Aggregate tables into company size categories and industry categories in backend
> feat: company size and industry aggregation

- backend/backend/settings.py
- client/src/components/company-input/company-input.tsx
- client/src/components/session-decrypt/decrypt-input.tsx
- client/src/components/session-manage/session-manage.tsx
- client/src/components/session-result/table-view.tsx
- client/src/guards/admin.guard.tsx
- client/src/pages/home.tsx
- client/src/utils/shamirs.ts
- Convert USD values to integers by multiplying by 100 before encrypting with SMPC.
- Divide by 100 after decrypting and reconstructing shares to get back units.
- Fixed CORS issue
- Remove console.logs
> feat: float values and handle CORS from issue #74

- client/src/components/footer.tsx
> Updated footer

- client/src/components/session-manage/generate-link.tsx
> Schema validator in the new participant input

- client/src/components/session-manage/session-manage-table.tsx
> Submission history

- client/src/components/session-result/table-view.tsx
> Selection shows only that exists in a result data

- backend/backend/apis/auth.py
- backend/backend/apis/bwwc.py
- backend/env/.env.dev
- backend/env/.env.example
Decode JWT using public key from AuthService API
> feat: jwt auth

- backend/backend/apis/bwwc.py
- backend/backend/settings.py
> feat: logging

- backend/requirements.txt
Added missing packages to requirements.txt
> fix: jose and requests

- backend/backend/apis/auth.py
- backend/backend/apis/bwwc.py
- backend/secretshare/mpce.py
Changed auth token to user id to check if initiator
> fix: is_initiator

- client/src/components/company-input/company-input.tsx
> validation schema changed

- backend/env/.env.dev
- backend/env/.env.example
- backend/secretshare/mpce.py
Production configuration settings for Redis
> Redis production config

- client/src/layouts/layout.tsx
- client/src/pages/create.tsx
- client/src/pages/manage.tsx
- deployment/docker-compose.production.yml
- deployment/docker-compose.staging.yml
- deployment/docker-compose.training.yml
> feat: mongo

- backend/requirements.txt
> chore: add pymongo

- client/src/utils/shamirs.ts
> fix: remove condition secret must be positive integer

- client/src/components/maintenance-banner.tsx
- client/src/layouts/layout.tsx
> warning banner added

- client/nginx.conf
> feat: backend nginx config

- client/nginx.conf
- deployment/docker-compose.production-backend.yml
- deployment/docker-compose.production-frontend.yml
> feat: create separate deployments for backend and frontend

- client/src/components/session-decrypt/decrypt-input.tsx
> text input of private key triggers decryption

- backend/backend/apis/bwwc.py
- backend/requirements.txt
- backend/sql/database.sql
> feat: add postgres connection

- backend/backend/apis/bwwc.py
- backend/secretshare/mpce.py
- client/src/components/session-manage/session-manage-table.tsx
> feat: add a second mongo collection for participant submissions

- backend/backend/apis/bwwc.py
- backend/sql/database.sql
> feat: add participant data to backup script

- client/cypress/e2e/submit-input.cy.ts
- client/cypress/support/custom/user-input.ts
- client/src/layouts/layout.tsx
> Experiment

- backend/secretshare/mpce.py
> fix: add logging

- client/src/pages/home.tsx
1. Check secretTable
2. Remove console.logs
> fix: should check secretTable not csvData
